spring.application.name=ssa

spring.datasource.url = jdbc:postgresql://localhost:5432/product_service2
spring.datasource.username = postgres
spring.datasource.password = root
spring.datasource.driver-class-name=org.postgresql.Driver