spring.application.name=ssa
server.port=7001


spring.datasource.url = jdbc:postgresql://localhost:5432/monolithic
spring.datasource.username = postgres
spring.datasource.password = root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgresPlusDialect
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
